    $('.owl-carousel-films').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        dots: false,
        responsive:{
            0:{
                items:2,
                nav:true
            },
            550:{
                items:3,
                nav:true
            },
            768:{
                items:4,
                nav:true,
                loop:true
            }
        }
    })

    $('.owl-carousel-channels').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        dots: false,
        responsive:{
            0:{
                items:1,
                nav:true
            },
            380:{
                items:2,
                margin:15,
                nav:true
            },
                768:{
                    items:3,
                    margin:15,
                    nav:true
                },
                    991:{
                        items:5,
                        nav:true
                    },
                    1200:{
                        items:6,
                        nav:true,
                        loop:true
                    }
        }
    })
